### ISSUE TITLE
Tag is missing 

### ISSUE THREAD

**Issue by frankrousseau** [spiroid/cozy-nginx#1]
When I use the following command:

```
docker pull spiroid/nginx
```

It tells me that a tag is missing to perform this operation. By the way the command has a typo in your README. A `c` is missing to the docker command.

**Comment by spiroid** [comment]
hi @frankrousseau, happy to see you here :)

From what i can see in the line you paster above, the image name is wrong, it should be:

```
docker pull spiroid/cozy-nginx
```

thx for the typo, i updated the readme.

**Comment by frankrousseau** [comment]
Sorry but when I type with the right name, it doesn't work either.

**Comment by spiroid** [comment]
Ok i checked the docker hub and a weird error message was displayed with no logs, on the previous image build.
I triggered a new build and it should be working as expected now.

**Comment by frankrousseau** [comment]
ok awesome thank you! Have a look at what @patcito did from your Docker Compose file : https://github.com/patcito/docker-compose-cozy

**Comment by spiroid** [comment]
Thanks for the link, i started to work on a similar idea based on @woshilapin feedback on the cozy forum. It may be a better idea to just fork that repository after all :)

I'm closing this issue
